### ISSUE TITLE
[*] Planned milestones

### ISSUE THREAD

**Issue by somnisomni** [somnisomni/Twiper#1]
## Development
- [ ] `clean` command for **Tweet cleaning**
  - [ ] Multi-part `tweets.js` (`window.YTD.tweets.part1` and so on)
  - [ ] Twitter Circle tweets
  - [ ] Filtered cleaning
    - [ ] $> n$ or $< n$  Likes
    - [ ] $> n$ or $< n$ Retweets
    - [ ] $> n$ or $< n$ Replies
    - [ ] With/Without medias
    - [ ] Only RTs
- [ ] `clean-like` command for **Likes cleaning**

## Web Documentation
- [ ] How-To-Use
- [ ] Commands and parameters

## Publish
- [ ] Make releases with standalone executable file for Windows, Linux(, macOS)
